In [18]:
import numpy as np

### 1) Alturas  
i. No trecho de código abaixo, crie um ndarray chamado ```altura_em_centimetros``` transformando a lista ```lista_de_alturas``` em um ndarray do numpy com a função ```np.array()```  
ii. Crie um outro objeto ```altura_em_metros```, com os valores de ```altura_em_centimetros``` convertidos para metros.

In [1]:
lista_de_centimetros = list(range(170, 190, 5))
lista_de_centimetros

[170, 175, 180, 185]

In [7]:
# I. Criando um ndarray chamado altura_em_centimetros
lista_de_centimetros = list(range(170, 190, 5))
altura_em_centimetros = np.array(lista_de_centimetros)

# Exibindo os resultados
print("Altura em centímetros:", altura_em_centimetros)

Altura em centímetros: [170 175 180 185]


In [9]:
# II. Convertendo para metros e criando o objeto altura_em_metros
altura_em_metros = altura_em_centimetros / 100.0

# Exibindo os resultados
print("Altura em metros:", altura_em_metros)

Altura em metros: [1.7  1.75 1.8  1.85]


### 2) IMC  
i. Considere que pesos em Kg dessas pessoas, na mesma ortem, estão na lista pesos ```lista_pesos = [70, 75, 80, 85]```. Crie um **ndarray** chamado ```pesos``` com a função ```np.array()``` que contenha esses valores.  
ii. Utilizando o objeto que contém as alturas em metros e esse objeto que contém os respectivos pesos em quilos, calcule o IMC desses indivíduos utilizando a aritmética de arrays e guarde os resultados em um objeto chamado ```imc```.

In [11]:
lista_pesos = [70, 75, 80, 85]
lista_pesos
# seu código aqui
import numpy as np

# I. Criando um ndarray chamado pesos
lista_pesos = [70, 75, 80, 85]
pesos = np.array(lista_pesos)

# II. Calculando o IMC (Índice de Massa Corporal)
altura_em_metros = altura_em_centimetros / 100.0
imc = pesos / altura_em_metros**2

# Exibindo os resultados
print("Pesos em quilos:", pesos)
print("Alturas em metros:", altura_em_metros)
print("IMC:", imc)


Pesos em quilos: [70 75 80 85]
Alturas em metros: [1.7  1.75 1.8  1.85]
IMC: [24.22145329 24.48979592 24.69135802 24.83564646]


### 3) Endividamento

Cálculos de novas variáveis como endividamento total e comprometimento de renda são essenciais para a construção de modelos financeiros em ciência de dados. Áreas não financeiras terão cálculos semelhantes também. Vamos praticar:

Considere que o seguinte ndarray contém os dados de 4 pessoas, total a ser pago a empréstimos mensalmente e renda familiar:

| custo fixo | dívida financeira | renda familiar |
|:----:|:----:|:---|
| 3000  | 1000 | 6000 |
| 2500  | 2500 | 5500 |
| 1000  | 3000 | 7000 |
| 10000 | 5000 | 16000 |

i. Transforme a lista de listas ```dados_financeiros``` no ndarray ```nd_financeiros```.
> ``` dados_financeiros[[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]] ```

ii. Utilize o método ```.transpose ``` e certifique-se de que esse ndarray tenha uma linha por indivíduo e uma coluna por informação. Utilizando a indexação do numpy, imprima no output a segunda linha do array, depois a segunda coluna.

iii. Pratique aritmética com nearrays e calcule o endividamento total como:
$$endividamento\hspace{.2cm}total = \frac{custo \hspace{.2cm}fixo + dívida\hspace{.2cm}financeira}{renda\hspace{.2cm}familiar}$$
Guarde os resultados em uma variável chamada ```endividamento_total``` e verifique os resultados imprimindo o conteúdo dessa variável no output.

iv. Considere que há um erro de digitação que precisa ser corrigido: 3o indivíduo na verdade não possui renda familiar de R\\$7.000,00, mas sim R\\$ 10.000,00. Corrija esse valor e refaça os cálculos.

In [12]:
# lista dados_financeiros
dados_financeiros = [[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]]
dados_financeiros
#i) transforme essa lista em um ndarray

[[3000, 2500, 1000, 10000],
 [1000, 2500, 3000, 5000],
 [6000, 5500, 7000, 16000]]

In [17]:
# i. Transformando a lista de listas em um ndarray
dados_financeiros = np.array([[3000, 2500, 1000, 10000],
                              [1000, 2500, 3000, 5000],
                              [6000, 5500, 7000, 16000]])

# ii. Transpondo o ndarray e acessando a segunda linha e a segunda coluna
dados_transpostos = dados_financeiros.transpose()
segunda_linha = dados_transpostos[1]
segunda_coluna = dados_transpostos[:, 1]

# iii. Calculando o endividamento total
endividamento_total = dados_financeiros[0] + dados_financeiros[1] + dados_financeiros[2]

# iv. Corrigindo o valor do terceiro indivíduo na renda familiar
dados_financeiros[2, 2] = 10000
# Recalculando o endividamento total após a correção
endividamento_total_corrigido = dados_financeiros[0] + dados_financeiros[1] + dados_financeiros[2]

# Exibindo os resultados
print("i. ndarray dados_financeiros:")
print(dados_financeiros)

print("\nii. Segunda linha e segunda coluna do array transposto:")
print("Segunda linha:", segunda_linha)
print("Segunda coluna:", segunda_coluna)

print("\niii. Endividamento total antes da correção:")
print(endividamento_total)

print("\niv. Endividamento total após a correção:")
print(endividamento_total_corrigido)


i. ndarray dados_financeiros:
[[ 3000  2500  1000 10000]
 [ 1000  2500  3000  5000]
 [ 6000  5500 10000 16000]]

ii. Segunda linha e segunda coluna do array transposto:
Segunda linha: [2500 2500 5500]
Segunda coluna: [1000 2500 3000 5000]

iii. Endividamento total antes da correção:
[10000 10500 11000 31000]

iv. Endividamento total após a correção:
[10000 10500 14000 31000]


### 4) É muito comum precisarmos identificar valores especiais e darmos tratamento a eles quer seja alterando-os quer seja descartando-os.

O trecho de código abaixo gera um ndarray com números pseudo aleatórios. Considere que para efeitos do estudo que virá, devemos desconsiderar valores iguais a zero. Sendo assim:

i) crie um objeto ```bool_zero``` que traga uma sequencia de booleanos do mesmo tamanho que o objeto poi, e que vale ```True``` quando o valor de ```poi``` é zero, e ```False``` caso contrário.

ii) Conte quantos valores zero existem. Lembre-se de que no final das contas, ```True``` vale 1 para o Python, e ```False``` vale zero, então uma boa dica seria usar a função ```sum()```.

iii) Utilize a indexação booleana que você aprendeu para criar uma variável ```poi_nao_zero``` que aponta para os elementos de ```poi``` diferentes de zero. Dica: você vai pode inverter os elementos do objeto que criou em *ii)* ou escrever a comparação adequada.

In [19]:
# objeto poi - obs: o comando np.random.seed(1234) garante que o mesmo resultado será gerado sempre
np.random.seed(1234)
poi = np.random.poisson(3, 100)
poi

array([3, 3, 6, 2, 4, 5, 4, 4, 2, 0, 3, 3, 2, 8, 2, 3, 3, 3, 0, 4, 4, 2,
       6, 6, 0, 3, 4, 3, 5, 2, 1, 3, 2, 2, 3, 2, 4, 4, 5, 7, 3, 5, 3, 3,
       2, 2, 3, 6, 2, 2, 4, 3, 5, 2, 5, 3, 0, 2, 1, 1, 4, 4, 4, 6, 2, 4,
       1, 2, 5, 5, 3, 4, 1, 4, 1, 1, 7, 1, 2, 1, 3, 7, 0, 4, 4, 0, 6, 1,
       3, 4, 2, 5, 4, 5, 5, 3, 4, 6, 8, 2])

In [23]:
# Configurando a semente para garantir a reproducibilidade
np.random.seed(1234)

# i. Criando um objeto bool_zero com valores True para zero e False para outros valores
poi = np.random.poisson(3, 100)
bool_zero = (poi == 0)

# ii. Contando quantos valores zero existem
quantidade_zeros = np.sum(bool_zero)

# iii. Criando uma variável poi_nao_zero usando indexação booleana
poi_nao_zero = poi[~bool_zero]  # ~ inverte os valores True e False

# Exibindo os resultados
print("i. Objeto bool_zero:")
print(bool_zero)

print("\nii. Quantidade de valores zero:", quantidade_zeros)

print("\niii. Variável poi_nao_zero:")
print(poi_nao_zero)


i. Objeto bool_zero:
[False False False False False False False False False  True False False
 False False False False False False  True False False False False False
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False  True False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False  True False False False False False False False False False False
 False False False False]

ii. Quantidade de valores zero: 6

iii. Variável poi_nao_zero:
[3 3 6 2 4 5 4 4 2 3 3 2 8 2 3 3 3 4 4 2 6 6 3 4 3 5 2 1 3 2 2 3 2 4 4 5 7
 3 5 3 3 2 2 3 6 2 2 4 3 5 2 5 3 2 1 1 4 4 4 6 2 4 1 2 5 5 3 4 1 4 1 1 7 1
 2 1 3 7 4 4 6 1 3 4 2 5 4 5 5 3 4 6 8 2]
